//
//  DocumentMetadata451.swift
//  451Wallet
//
//  Created by User451 on 1/23/26.
//
//  Comprehensive metadata structure for the 451 protocol
//  Based on the full metadata schema from the thesis app
//

import Foundation
import Observation

/// Comprehensive metadata for 451 protocol documents
/// Aligned with Dublin Core and scholarly publishing metadata standards
public struct DocumentMetadata451: Codable, Equatable, Hashable {
    
    // MARK: - Core Identifiers

    /// Unique document identifier (UUID generated by client or server)
    public var id: String?

    /// Decentralized identifier for the document
    /// Example format: did:local:<UUID> or did:451:<hash>
    public var did: String?

    /// Digital Object Identifier (DOI) for academic publications
    public var doi: String?

    /// ISBN for books
    public var isbn: String?

    /// ISSN for periodicals
    public var issn: String?

    /// Generic identifier field for other identification schemes
    public var identifier: String?

    // MARK: - Descriptive Metadata

    /// Primary title of the document
    public var title: String?

    /// Secondary title or explanatory subtitle
    public var subtitle: String?

    /// Full description or abstract
    public var description: String?

    /// Subject matter, keywords, or topics (comma-separated or array)
    public var subject: String?

    /// Document type (e.g., "contract", "article", "book", "report")
    public var type: String?

    /// Language of the document content (ISO 639 code recommended)
    public var language: String?

    /// Full transcript of the document (for audio/video content)
    public var transcript: String?

    // MARK: - Responsibility (Dublin Core Creator/Contributor)

    /// Primary author(s) - comma-separated string or use signers array for structured data
    public var author: String?

    /// Contributors who are not primary authors
    public var contributor: String?

    /// Publisher of the document
    public var publisher: String?

    // MARK: - Rights & Access

    /// Rights statement or license
    public var rights: String?

    /// Person or organization holding rights
    public var rightsholder: String?

    /// Access rights description (e.g., "public", "private", "restricted")
    public var accessrights: String?

    // MARK: - Dates

    /// Date of publication
    public var publicationDate: String?

    /// Date the document becomes available
    public var dateAvailable: String?

    // MARK: - Audience & Context

    /// Target audience description
    public var audience: String?

    /// Mediator or intermediary for the audience
    public var audiencemediator: String?

    /// Provenance or historical record of ownership/custody
    public var provenance: String?

    // MARK: - Format & Technical

    /// Format description (e.g., "451", "PDF", "DOCX")
    public var format: String?

    /// Original file extension if uploaded
    public var fileExtension: String?

    /// MIME type of the original file
    public var mimeType: String?

    /// Size in bytes of the original document
    public var fileSize: Int?

    /// Cryptographic hash of the document content
    public var documentHash: String?

    // MARK: - Structured Signers (for multi-party signing)

    /// Array of signers with their roles
    public var signers: [SignerMetadata]?

    /// Signer metadata structure
    public struct SignerMetadata: Codable, Equatable, Hashable {
        public var did: String
        public var role: String  // "author", "contractParty", "witness", "notary", "reviewer"
        public var publicKey: String?
        public var displayName: String?

        public init(did: String, role: String, publicKey: String? = nil, displayName: String? = nil) {
            self.did = did
            self.role = role
            self.publicKey = publicKey
            self.displayName = displayName
        }
    }

    // MARK: - Legacy/Additional Fields

    /// Contract-specific identifier
    public var contractId: String?

    /// Custom tags or categories
    public var tags: [String]?

    /// Custom key-value metadata
    public var customFields: [String: String]?

    // MARK: - Fill-in Variables (search index 3)

    /// The document's `entity_type = variable` objects, produced by the carrier's ingest walk and
    /// embedded here at publish so the server can populate index 3 without re-parsing the body.
    /// Nil (not `[]`) when the document has no fill-in slots. See `VariableIndexObject`.
    public var variables: [VariableIndexObject]?

    // MARK: - Initializer

    public init(
        id: String? = nil,
        did: String? = nil,
        title: String? = nil,
        subtitle: String? = nil,
        description: String? = nil,
        author: String? = nil,
        subject: String? = nil,
        type: String? = nil,
        language: String? = "English",
        format: String? = "451",
        signers: [SignerMetadata]? = nil
    ) {
        self.id = id
        self.did = did
        self.title = title
        self.subtitle = subtitle
        self.description = description
        self.author = author
        self.subject = subject
        self.type = type
        self.language = language
        self.format = format
        self.signers = signers
    }
    
    // MARK: - Convenience Methods
    /// Create from signer selections
    public static func from(signers: [SignerSelection]) -> [SignerMetadata] {
        return signers.map { selection in
            SignerMetadata(
                did: selection.did,
                role: selection.role.rawValue,
                publicKey: nil,
                displayName: nil
            )
        }
    }
}

// MARK: - Metadata Form Model

/// SwiftUI form model for collecting metadata from users
@Observable
public class DocumentMetadataForm {
    public var title: String = ""
    public var subtitle: String = ""
    public var description: String = ""
    public var author: String = ""
    public var subject: String = ""
    public var type: String = ""
    public var language: String = "English"
    public var audience: String = ""
    public var rights: String = ""
    public var accessrights: String = "private"
    public var publicationDate: String = ""
    public var publisher: String = ""
    public var doi: String = ""
    public var isbn: String = ""
    public var contractId: String = ""

    public init() {}

    /// Convert form values to DocumentMetadata451
    public func toMetadata() -> DocumentMetadata451 {
        var metadata = DocumentMetadata451()
        
        // Only include non-empty fields
        if !title.isEmpty { metadata.title = title }
        if !subtitle.isEmpty { metadata.subtitle = subtitle }
        if !description.isEmpty { metadata.description = description }
        if !author.isEmpty { metadata.author = author }
        if !subject.isEmpty { metadata.subject = subject }
        if !type.isEmpty { metadata.type = type }
        if !language.isEmpty { metadata.language = language }
        if !audience.isEmpty { metadata.audience = audience }
        if !rights.isEmpty { metadata.rights = rights }
        if !accessrights.isEmpty { metadata.accessrights = accessrights }
        if !publicationDate.isEmpty { metadata.publicationDate = publicationDate }
        if !publisher.isEmpty { metadata.publisher = publisher }
        if !doi.isEmpty { metadata.doi = doi }
        if !isbn.isEmpty { metadata.isbn = isbn }
        if !contractId.isEmpty { metadata.contractId = contractId }
        
        return metadata
    }
    
    /// Populate form from existing metadata
    public func populate(from metadata: DocumentMetadata451) {
        title = metadata.title ?? ""
        subtitle = metadata.subtitle ?? ""
        description = metadata.description ?? ""
        author = metadata.author ?? ""
        subject = metadata.subject ?? ""
        type = metadata.type ?? ""
        language = metadata.language ?? "English"
        audience = metadata.audience ?? ""
        rights = metadata.rights ?? ""
        accessrights = metadata.accessrights ?? "private"
        publicationDate = metadata.publicationDate ?? ""
        publisher = metadata.publisher ?? ""
        doi = metadata.doi ?? ""
        isbn = metadata.isbn ?? ""
        contractId = metadata.contractId ?? ""
    }
}
