//
//  DocumentMetadata451.swift
//  451Wallet
//
//  Created by User451 on 1/23/26.
//
//  Comprehensive metadata structure for the 451 protocol
//  Based on the full metadata schema from the thesis app
//

import Foundation

/// Comprehensive metadata for 451 protocol documents
/// Aligned with Dublin Core and scholarly publishing metadata standards
public struct DocumentMetadata451: Codable, Equatable, Hashable {
    
    // MARK: - Core Identifiers
    
    /// Unique document identifier (UUID generated by client or server)
    var id: String?
    
    /// Decentralized identifier for the document
    /// Example format: did:local:<UUID> or did:451:<hash>
    var did: String?
    
    /// Digital Object Identifier (DOI) for academic publications
    var doi: String?
    
    /// ISBN for books
    var isbn: String?
    
    /// ISSN for periodicals
    var issn: String?
    
    /// Generic identifier field for other identification schemes
    var identifier: String?
    
    // MARK: - Descriptive Metadata
    
    /// Primary title of the document
    var title: String?
    
    /// Secondary title or explanatory subtitle
    var subtitle: String?
    
    /// Full description or abstract
    var description: String?
    
    /// Subject matter, keywords, or topics (comma-separated or array)
    var subject: String?
    
    /// Document type (e.g., "contract", "article", "book", "report")
    var type: String?
    
    /// Language of the document content (ISO 639 code recommended)
    var language: String?
    
    /// Full transcript of the document (for audio/video content)
    var transcript: String?
    
    // MARK: - Responsibility (Dublin Core Creator/Contributor)
    
    /// Primary author(s) - comma-separated string or use signers array for structured data
    var author: String?
    
    /// Contributors who are not primary authors
    var contributor: String?
    
    /// Publisher of the document
    var publisher: String?
    
    // MARK: - Rights & Access
    
    /// Rights statement or license
    var rights: String?
    
    /// Person or organization holding rights
    var rightsholder: String?
    
    /// Access rights description (e.g., "public", "private", "restricted")
    var accessrights: String?
    
    // MARK: - Dates
    
    /// Date of publication
    var publicationDate: String?
    
    /// Date the document becomes available
    var dateAvailable: String?
    
    // MARK: - Audience & Context
    
    /// Target audience description
    var audience: String?
    
    /// Mediator or intermediary for the audience
    var audiencemediator: String?
    
    /// Provenance or historical record of ownership/custody
    var provenance: String?
    
    // MARK: - Format & Technical
    
    /// Format description (e.g., "451", "PDF", "DOCX")
    var format: String?
    
    /// Original file extension if uploaded
    var fileExtension: String?
    
    /// MIME type of the original file
    var mimeType: String?
    
    /// Size in bytes of the original document
    var fileSize: Int?
    
    /// Cryptographic hash of the document content
    var documentHash: String?
    
    // MARK: - Structured Signers (for multi-party signing)
    
    /// Array of signers with their roles
    var signers: [SignerMetadata]?
    
    /// Signer metadata structure
    struct SignerMetadata: Codable, Equatable, Hashable {
        var did: String
        var role: String  // "author", "contractParty", "witness", "notary", "reviewer"
        var publicKey: String?
        var displayName: String?
    }
    
    // MARK: - Legacy/Additional Fields
    
    /// Contract-specific identifier
    var contractId: String?
    
    /// Custom tags or categories
    var tags: [String]?
    
    /// Custom key-value metadata
    var customFields: [String: String]?
    
    // MARK: - Initializer
    
    init(
        id: String? = nil,
        did: String? = nil,
        title: String? = nil,
        subtitle: String? = nil,
        description: String? = nil,
        author: String? = nil,
        subject: String? = nil,
        type: String? = nil,
        language: String? = "English",
        format: String? = "451",
        signers: [SignerMetadata]? = nil
    ) {
        self.id = id
        self.did = did
        self.title = title
        self.subtitle = subtitle
        self.description = description
        self.author = author
        self.subject = subject
        self.type = type
        self.language = language
        self.format = format
        self.signers = signers
    }
    
    // MARK: - Convenience Methods
    /// Create from signer selections
    static func from(signers: [SignerSelection]) -> [SignerMetadata] {
        return signers.map { selection in
            SignerMetadata(
                did: selection.did,
                role: selection.role.rawValue,
                publicKey: nil,
                displayName: nil
            )
        }
    }
}

// MARK: - Metadata Form Model

/// SwiftUI form model for collecting metadata from users
@Observable
class DocumentMetadataForm {
    var title: String = ""
    var subtitle: String = ""
    var description: String = ""
    var author: String = ""
    var subject: String = ""
    var type: String = ""
    var language: String = "English"
    var audience: String = ""
    var rights: String = ""
    var accessrights: String = "private"
    var publicationDate: String = ""
    var publisher: String = ""
    var doi: String = ""
    var isbn: String = ""
    var contractId: String = ""
    
    /// Convert form values to DocumentMetadata451
    func toMetadata() -> DocumentMetadata451 {
        var metadata = DocumentMetadata451()
        
        // Only include non-empty fields
        if !title.isEmpty { metadata.title = title }
        if !subtitle.isEmpty { metadata.subtitle = subtitle }
        if !description.isEmpty { metadata.description = description }
        if !author.isEmpty { metadata.author = author }
        if !subject.isEmpty { metadata.subject = subject }
        if !type.isEmpty { metadata.type = type }
        if !language.isEmpty { metadata.language = language }
        if !audience.isEmpty { metadata.audience = audience }
        if !rights.isEmpty { metadata.rights = rights }
        if !accessrights.isEmpty { metadata.accessrights = accessrights }
        if !publicationDate.isEmpty { metadata.publicationDate = publicationDate }
        if !publisher.isEmpty { metadata.publisher = publisher }
        if !doi.isEmpty { metadata.doi = doi }
        if !isbn.isEmpty { metadata.isbn = isbn }
        if !contractId.isEmpty { metadata.contractId = contractId }
        
        return metadata
    }
    
    /// Populate form from existing metadata
    func populate(from metadata: DocumentMetadata451) {
        title = metadata.title ?? ""
        subtitle = metadata.subtitle ?? ""
        description = metadata.description ?? ""
        author = metadata.author ?? ""
        subject = metadata.subject ?? ""
        type = metadata.type ?? ""
        language = metadata.language ?? "English"
        audience = metadata.audience ?? ""
        rights = metadata.rights ?? ""
        accessrights = metadata.accessrights ?? "private"
        publicationDate = metadata.publicationDate ?? ""
        publisher = metadata.publisher ?? ""
        doi = metadata.doi ?? ""
        isbn = metadata.isbn ?? ""
        contractId = metadata.contractId ?? ""
    }
}
